install:
  - curl --user "$GITHUB_USER:$GITHUB_TOKEN" https://api.github.com/repos/netlify/netlifyctl/releases/latest
  - curl --user "$GITHUB_USER:$GITHUB_TOKEN" https://api.github.com/repos/netlify/netlifyctl/releases/latest | jq '.assets[] | select(.name | contains("netlifyctl-linux-amd64-0.4.0.tar.gz"))? | .url'
  - wget --header='Accept:application/octet-stream' --user=$GITHUB_USER:$GITHUB_TOKEN https://api.github.com/repos/netlify/netlifyctl/releases/assets/6273453 -O netlifyctl-linux-amd64-0.3.2.tar.gz
  - false && tar -xzvf netlifyctl-linux-amd64-0.3.2.tar.gz
script:
  - ls -al
  - ./netlifyctl --help
